---
name: "Release"

on:
  push:
    tags:
      # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - 'v2[0-1][0-9][0-9].0[0-9].[0-9][0-9]'
      - 'v2[0-1][0-9][0-9].1[0-2].[0-9][0-9]'

env:
  python_version: "3.9"

jobs:
  distribute:
    name: Distribute
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Retrieve the tag
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> "${GITHUB_ENV}"
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version }}
      - uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ env.python_version }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ env.python_version }}-pipenv-
            ${{ runner.os }}-python-
      - name: Install the dependencies
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --deploy --ignore-pipfile --dev
      - name: Build the image(s)
        run: pipenv run invoke build
      - name: Publish the release to GitHub
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.TAG }}
          draft: false
          prerelease: false